---
collections:
#- name: https://github.com/c2platform/ansible-collection-core.git
#  version: v1.0.0
#  type: git
#  #source: https://github.com/c2platform/ansible-collection-core.git
- name: sindhuparvathi_gopi.ansible_collection_template
  version: 1.0.2
