---
- name: desktop.yml
  hosts: desktop
  become: yes

  roles:
    - { role: common,                       tags: ["common"] }
    - { role: geerlingguy.docker,           tags: ["docker"] }
    - { role: postgresql_client,            tags: ["database"] }
    - { role: docker,                       tags: ["docker"] }
    - { role: guacamole,                    tags: ["guacamole"] }
    - { role: desktop,                      tags: ["desktop"] }    
    - { role: backup,                       tags: ["backup"] }
