---
- name: oracle.yml
  hosts: oracle
  become: yes

  roles:
    - { role: common,                       tags: ["common"] }
    - { role: geerlingguy.docker,           tags: ["oracle", "docker"] }
    - { role: docker,                       tags: ["docker"] }
    - { role: oracle-database,              tags: ["oracle", "docker"] }
    - { role: oracle_client,                tags: ["oracle", "docker"] }
